version: '3.8'

services:
  flask:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - flask
